version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/usr/src/app
      - /usr/src/app/node_modules
      - /usr/src/app/.next
    environment:
      - NEXT_PUBLIC_API_URL=http://backend:8000
      # - NODE_ENV=development # Uncomment if needed for specific dev setup
    depends_on:
      - backend
    restart: unless-stopped
    networks:
      - planeats_network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    environment:
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@$localhost:5432/${POSTGRES_DB}
    depends_on:
      - db
    restart: unless-stopped
    networks:
      - planeats_network

  db:
    image: postgres:13-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    restart: unless-stopped
    networks:
      - planeats_network

volumes:
  postgres_data:

networks:
  planeats_network:
    driver: bridge
