"""add_image_url_to_pantryitem

Revision ID: 7775bfacd9f6
Revises: c1516b67634a 
Create Date: 2025-06-13 17:03:00.000000 

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel # Add this line


# revision identifiers, used by Alembic.
revision: str = '7775bfacd9f6'
down_revision: Union[str, None] = '95eac7b8909b' # Ensure this points to the previous migration
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pantryitem', sa.Column('image_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pantryitem', 'image_url')
    # ### end Alembic commands ###
