"""add_disliked_ingredients_to_userpreference

Revision ID: 95eac7b8909b
Revises: c1516b67634a
Create Date: 2025-06-12 20:37:01.977799

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '95eac7b8909b'
down_revision: Union[str, None] = 'c1516b67634a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # JSON columns like disliked_ingredients, notification_preferences, other_preferences, cuisine_preferences
    # are assumed to exist from prior (possibly partial) migration runs.
    # Adding simple type columns that might still be missing.
    # daily_calorie_goal column already exists, so it's removed from this migration's scope.
    op.add_column('userpreference', sa.Column('preferred_difficulty', sa.String(), nullable=True))
    op.add_column('userpreference', sa.Column('max_prep_time_preference', sa.Integer(), nullable=True))
    op.add_column('userpreference', sa.Column('max_calories_preference', sa.Integer(), nullable=True))
    op.add_column('userpreference', sa.Column('avoid_missing_ingredients', sa.Boolean(), nullable=True, server_default=sa.text('false')))
    op.add_column('userpreference', sa.Column('prioritize_expiring_ingredients', sa.Boolean(), nullable=True, server_default=sa.text('true')))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Corresponding drop operations for the simple type columns.
    op.drop_column('userpreference', 'prioritize_expiring_ingredients')
    op.drop_column('userpreference', 'avoid_missing_ingredients')
    op.drop_column('userpreference', 'max_calories_preference')
    op.drop_column('userpreference', 'max_prep_time_preference')
    op.drop_column('userpreference', 'preferred_difficulty')
    # daily_calorie_goal was not added by this migration's upgrade path.
    # Note: JSON columns dropped here previously are removed as they were assumed to exist.
    # If they were added by this script's earlier versions, this downgrade is now incomplete for those.
    # For safety, keeping the downgrade focused on what this version of upgrade() does.
    # ### end Alembic commands ###
