"""add_cuisine_preferences_to_userpreference

Revision ID: c1516b67634a
Revises: 6c819394c7da
Create Date: 2025-06-12 20:33:20.335751

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c1516b67634a'
down_revision: Union[str, None] = '6c819394c7da'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('userpreference', sa.Column('cuisine_preferences', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('userpreference', 'cuisine_preferences')
    # ### end Alembic commands ###
